import { Geist, Geist_Mono, Karla } from "next/font/google";
import "../main.scss";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import Pagewrapper from "@/components/pagewrapper";

const karla = Karla({
  variable: "--font-karla",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}${karla.variable} antialiased`}
      >
        <Sidebar></Sidebar>
        <Header></Header>
        <Pagewrapper>{children}</Pagewrapper>
      </body>
    </html>
  );
}
